import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gudea = localFont({
  src: [
    {
      path: "./fonts/Gudea-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gudea-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-gudea",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={gudea.variable}>
        {children}
      </body>
    </html>
  );
}